routes/web.php
<?php

/**
 * Authentication
 */
Route::get('login', 'Auth\LoginController@show');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout')->name('auth.logout');

Route::group(['middleware' => ['registration', 'guest']], function () {
    Route::get('register', 'Auth\RegisterController@show');
    Route::post('register', 'Auth\RegisterController@registerDirection');
});

Route::emailVerification();

Route::group(['middleware' => ['password-reset', 'guest']], function () {
    Route::resetPassword();
});

/**
 * Two-Factor Authentication
 */
Route::group(['middleware' => 'two-factor'], function () {
    Route::get('auth/two-factor-authentication', 'Auth\TwoFactorTokenController@show')->name('auth.token');
    Route::post('auth/two-factor-authentication', 'Auth\TwoFactorTokenController@update')->name('auth.token.validate');
});

/**
 * Social Login
 */
Route::get('auth/{provider}/login', 'Auth\SocialAuthController@redirectToProvider')->name('social.login');
Route::get('auth/{provider}/callback', 'Auth\SocialAuthController@handleProviderCallback');

Route::group(['middleware' => ['auth', 'verified']], function () {

    /**
     * Impersonate Routes
     */
    Route::impersonate();

    /**
     * Dashboard
     */

    Route::get('/', 'DashboardController@index')->name('dashboard');

    /**
     * User Profile
     */

    Route::group(['prefix' => 'profile', 'namespace' => 'Profile'], function () {
        Route::get('/', 'ProfileController@show')->name('profile');
        Route::get('activity', 'ActivityController@show')->name('profile.activity');
        Route::put('details', 'DetailsController@update')->name('profile.update.details');

        Route::post('avatar', 'AvatarController@update')->name('profile.update.avatar');
        Route::post('avatar/external', 'AvatarController@updateExternal')
            ->name('profile.update.avatar-external');

        Route::put('login-details', 'LoginDetailsController@update')
            ->name('profile.update.login-details');

        Route::get('sessions', 'SessionsController@index')
            ->name('profile.sessions')
            ->middleware('session.database');

        Route::delete('sessions/{session}/invalidate', 'SessionsController@destroy')
            ->name('profile.sessions.invalidate')
            ->middleware('session.database');
    });

    /**
     * Two-Factor Authentication Setup
     */

    Route::group(['middleware' => 'two-factor'], function () {
        Route::post('two-factor/enable', 'TwoFactorController@enable')->name('two-factor.enable');

        Route::get('two-factor/verification', 'TwoFactorController@verification')
            ->name('two-factor.verification')
            ->middleware('verify-2fa-phone');

        Route::post('two-factor/resend', 'TwoFactorController@resend')
            ->name('two-factor.resend')
            ->middleware('throttle:1,1', 'verify-2fa-phone');

        Route::post('two-factor/verify', 'TwoFactorController@verify')
            ->name('two-factor.verify')
            ->middleware('verify-2fa-phone');

        Route::post('two-factor/disable', 'TwoFactorController@disable')->name('two-factor.disable');
    });



    /**
     * User Management
     */
    Route::resource('users', 'Users\UsersController')
        ->except('update')->middleware('permission:users.manage');

    Route::group(['prefix' => 'users/{user}', 'middleware' => 'permission:users.manage'], function () {
        Route::put('update/details', 'Users\DetailsController@update')->name('users.update.details');
        Route::put('update/login-details', 'Users\LoginDetailsController@update')
            ->name('users.update.login-details');

        Route::post('update/avatar', 'Users\AvatarController@update')->name('user.update.avatar');
        Route::post('update/avatar/external', 'Users\AvatarController@updateExternal')
            ->name('user.update.avatar.external');

        Route::get('sessions', 'Users\SessionsController@index')
            ->name('user.sessions')->middleware('session.database');

        Route::delete('sessions/{session}/invalidate', 'Users\SessionsController@destroy')
            ->name('user.sessions.invalidate')->middleware('session.database');

        Route::post('two-factor/enable', 'TwoFactorController@enable')->name('user.two-factor.enable');
        Route::post('two-factor/disable', 'TwoFactorController@disable')->name('user.two-factor.disable');
    });

    /**
     * Directions Management
     */

    Route::resource('directions', 'DirectionsController')->middleware('permission:directions.manage');

    /**
     * File Manager
     */

    Route::group(['prefix' => 'files', 'middleware' => 'permission:files.create'], function () {


        Route::get('/', 'Files\FilesController@index')
            ->name('files.index');

        Route::post('/store', 'Files\FilesController@store')
            ->name('files.store');

        Route::post('/scanner/store', 'Files\FilesController@documentScannerData')
            ->name('files.scanner');

        Route::get('/{file}/edit', 'Files\FilesController@edit')
            ->name('files.edit');

        Route::put('/{file}/update', 'Files\FilesController@update')
            ->name('files.update');

        Route::get('/download',function(){
        $file = public_path()."/scannerApp/Setup.msi";
        return Response::download($file,'Setup.msi');
        })->name('files.download-app');

        Route::get('autocomplete', 'Files\FilesController@autocomplete')->name('autocomplete');
        Route::get('prefetch', 'Files\FilesController@autocompletePrefetch')->name('prefetch');

        Route::get('prefetch', 'Files\FilesController@autocompletePrefetch')->name('prefetch');

        Route::get('list-view', 'Files\FilesController@listView')->name('list.view');

    });

    /**
     * Roles & Permissions
     */
    Route::group(['namespace' => 'Authorization'], function () {
        Route::resource('roles', 'RolesController')->except('show')->middleware('permission:roles.manage');

        Route::post('permissions/save', 'RolePermissionsController@update')
            ->name('permissions.save')
            ->middleware('permission:permissions.manage');

        Route::resource('permissions', 'PermissionsController')->middleware('permission:permissions.manage');
    });


    /**
     * Settings
     */

    Route::post('dark-mode', 'SettingsController@darkMode')->name('setting.dark');

    Route::get('settings', 'SettingsController@general')->name('settings.general')
        ->middleware('permission:settings.general');

    Route::post('settings/general', 'SettingsController@update')->name('settings.general.update')
        ->middleware('permission:settings.general');

    Route::get('settings/auth', 'SettingsController@auth')->name('settings.auth')
        ->middleware('permission:settings.auth');

    Route::post('settings/auth', 'SettingsController@update')->name('settings.auth.update')
        ->middleware('permission:settings.auth');

    if (config('services.authy.key')) {
        Route::post('settings/auth/2fa/enable', 'SettingsController@enableTwoFactor')
            ->name('settings.auth.2fa.enable')
            ->middleware('permission:settings.auth');

        Route::post('settings/auth/2fa/disable', 'SettingsController@disableTwoFactor')
            ->name('settings.auth.2fa.disable')
            ->middleware('permission:settings.auth');
    }

    Route::post('settings/auth/registration/captcha/enable', 'SettingsController@enableCaptcha')
        ->name('settings.registration.captcha.enable')
        ->middleware('permission:settings.auth');

    Route::post('settings/auth/registration/captcha/disable', 'SettingsController@disableCaptcha')
        ->name('settings.registration.captcha.disable')
        ->middleware('permission:settings.auth');

    Route::get('settings/notifications', 'SettingsController@notifications')
        ->name('settings.notifications')
        ->middleware('permission:settings.notifications');

    Route::post('settings/notifications', 'SettingsController@update')
        ->name('settings.notifications.update')
        ->middleware('permission:settings.notifications');

    /**
     * Activity Log
     */

    Route::get('activity', 'ActivityController@index')->name('activity.index')
        ->middleware('permission:users.activity');

    Route::get('activity/user/{user}/log', 'Users\ActivityController@index')->name('activity.user')
        ->middleware('permission:users.activity');
});


/**
 * Installation
 */

Route::group(['prefix' => 'install'], function () {
    Route::get('/', 'InstallController@index')->name('install.start');
    Route::get('requirements', 'InstallController@requirements')->name('install.requirements');
    Route::get('permissions', 'InstallController@permissions')->name('install.permissions');
    Route::get('database', 'InstallController@databaseInfo')->name('install.database');
    Route::get('start-installation', 'InstallController@installation')->name('install.installation');
    Route::post('start-installation', 'InstallController@installation')->name('install.installation');
    Route::post('install-app', 'InstallController@install')->name('install.install');
    Route::get('complete', 'InstallController@complete')->name('install.complete');
    Route::get('error', 'InstallController@error')->name('install.error');
});

app/Direction.php
<?php

namespace Kouloughli;

use Illuminate\Database\Eloquent\Model;
use Kouloughli\Presenters\DirectionPresenter;
use Kouloughli\Presenters\Traits\Presentable;

class Direction extends Model
{
    use  Presentable;
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'directions';
    protected $primaryKey = 'id_direc';
    protected $presenter = DirectionPresenter::class;




    protected $fillable = ['direc_name', 'direc_description','direc_email',
        'direc_phone','direc_status','folder_path'];


    /**
     * Get All Users of direction
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function users()
    {
        return $this->hasMany(User::class, 'id_direc','id_direc');
    }


    /**
     * Get Ids of users in direction
     * @return mixed
     */
    public function getUserIdsAttribute()
    {
        return $this->users->pluck('ref_user');
    }


    /**
     * Get All Files For Directions
     * @return \Illuminate\Database\Eloquent\Relations\HasManyThrough
     */
    public function files()
    {
        return $this->hasManyThrough(File::class,User::class,'id_direc'
            , 'ref_user','id_direc','ref_user');
    }
}

app/Http/Controllers/Web/DirectionsController.php
<?php

namespace Kouloughli\Http\Controllers\Web;

use Kouloughli\Direction;
use Kouloughli\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Kouloughli\Http\Requests\Direction\CreateDirectionRequest;
use Kouloughli\Http\Requests\Direction\RemoveDirectionRequest;
use Kouloughli\Http\Requests\Direction\UpdateDirectionRequest;
use Kouloughli\Repositories\Direction\DirectionRepository;
use Kouloughli\Repositories\Role\RoleRepository;
use Kouloughli\Repositories\User\UserRepository;
use Kouloughli\Support\Enum\DirectionStatus;
use Kouloughli\Support\Enum\UserStatus;

class DirectionsController extends Controller
{
    /**
     * @var DirectionRepository
     */
    private $directions;
    /**
     * @var UserRepository
     */
    private $user;
    /**
     * @var RoleRepository
     */
    private $role;

    /**
     * DirectionsController constructor.
     * @param DirectionRepository $directionRepository
     */
    public function __construct(DirectionRepository $directionRepository,UserRepository $userRepository,RoleRepository $roleRepository)
    {
        $this->middleware('auth');
        $this->directions = $directionRepository;
        $this->user = $userRepository;
        $this->role = $roleRepository;
    }

    /**
     * List Of all direction in GED Mila
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $directions = $this->directions->paginate($perPage = 20, $request->search, $request->status);

        $statuses = ['' => __('All')] + DirectionStatus::lists();

        return view('direction.list', compact('directions', 'statuses'));
    }


    /**
     * View Details for specific direction
     *
     * @param Direction $direction
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Direction $direction)
    {
        return view('direction.view',compact('direction'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('direction.add');
    }

    /**
     * @param CreateDirectionRequest $request
     * @return mixed
     */
    public function store(CreateDirectionRequest $request)
    {
        // When Direction is created by administrator, we will set his
        // status to Active by default.
        $data = $request->all() + [
                'direc_status' => DirectionStatus::ACTIVE,
                'folder_path' => $this->directions->generateDirectoryName(),
            ];
        $direction = $this->directions->create($data);

        // Create User for direction
        $role = $this->role->findByName('User');
        $userData = $request->all() + [
                'status' => UserStatus::ACTIVE,
                'id_direc' => $direction->id_direc,
                'role_id' => $role->ref_role,
                'email_verified_at' => now()
            ];
        $this->user->create($userData);

        return redirect()->route('directions.index')
            ->withSuccess(__('Direction created successfully.'));
    }


    /**
     * @param Direction $direction
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Direction $direction)
    {
        return view('direction.edit',[
            'edit' => true,
            'direction' => $direction,
            'statuses' => DirectionStatus::lists()
        ]);
    }


    /**
     * @param Direction $direction
     * @param UpdateDirectionRequest $request
     * @return mixed
     */
    public function update(Direction $direction,UpdateDirectionRequest $request)
    {
        $data = $request->all();
        $this->directions->update($direction->id_direc,$data);

        return redirect()->back()
            ->withSuccess(__('Direction updated successfully.'));
    }


    public function destroy(RemoveDirectionRequest $request,Direction $direction)
    {
        $userDirection = auth()->user()->direction;
        if ($userDirection->is($direction) || $direction->id_direc == 1 ) {
            return redirect()->route('directions.index')
                ->withErrors(__('You cannot delete you direction.'));
        }

        $this->directions->delete($direction->id_direc);

        //event(new Deleted($user));

        return redirect()->route('directions.index')
            ->withSuccess(__('User deleted successfully.'));
    }


}

resources/views/direction/partials/details.blade.php
<div class="row">
    <div class="col-md-12">


        @if ($edit)
        <div class="form-group">
            <label for="direc_status">@lang('Status')</label>
            {!! Form::select('direc_status', $statuses, $edit ? $direction->direc_status : '',
                ['class' => 'custom-select', 'id' => 'direc_status', !$edit ? 'disabled' : '']) !!}
        </div>
        @endif

        <div class="form-group">
            <label for="direc_name">@lang('Direction Name')</label>
            <input type="text" class="form-control input-solid" id="direc_name"
                   name="direc_name" placeholder="@lang('Direction Name')" value="{{ $edit ? $direction->direc_name : old('direc_name') }}">
        </div>

        <div class="form-group">
            <label for="direc_description">@lang('Direction Description')</label>
            <input type="text" class="form-control input-solid" id="direc_description"
                   name="direc_description" placeholder="@lang('Direction Description')" value="{{ $edit ? $direction->direc_description : old('direc_description') }}">
        </div>

        <div class="form-group">
            <label for="direc_email">@lang('Direction Email')</label>
            <input type="text" class="form-control input-solid" id="direc_email"
                   name="direc_email" placeholder="@lang('Direction Email')" value="{{ $edit ? $direction->direc_email : old('direc_email') }}">
        </div>

        <div class="form-group">
            <label for="direc_phone">@lang('Direction Phone')</label>
            <input type="text" class="form-control input-solid" id="direc_phone"
                   name="direc_phone" placeholder="@lang('Direction Phone')" value="{{ $edit ? $direction->direc_phone : old('direc_phone') }}">
        </div>
    </div>

    @if ($edit)
        <div class="col-md-12 mt-2">
            <button type="submit" class="btn btn-primary  btn-block" id="update-details-btn">
                <i class="fa fa-refresh"></i>
                @lang('Update Details')
            </button>
        </div>
    @endif
</div>

resources/views/direction/partials/row.blade.php
<tr>
    <td class="align-middle">
        <a href="#">
            {{ $direction->direc_name ?: __('N/A') }}
        </a>
    </td>
    <td class="align-middle">{{ $direction->direc_description}}</td>
    <td class="align-middle">{{ $direction->direc_email }}</td>
    <td class="align-middle">{{ $direction->direc_phone }}</td>
    <td class="align-middle text-center">{{ $direction->files_count }}</td>
    <td class="align-middle">{{ $direction->created_at->format(config('app.date_format')) }}</td>
    <td class="align-middle">
        <span class="badge  badge-{{ $direction->present()->labelClass }}">
            {{ trans("app.status.{$direction->direc_status}") }}
        </span>
    </td>
    <td class="text-center align-middle">

        <div class="dropdown show d-inline-block dropdown-file">
            <a class="btn btn-icon"
               href="#" role="button" id="dropdownMenuLink"
               data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                <i data-feather="more-vertical"></i>
            </a>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                @canBeImpersonated($direction->users[0])
                <a href="{{ route('impersonate', $direction->users[0]) }}"  class="dropdown-item impersonate">
                    <i data-feather="lock"></i>@lang('Impersonate')
                </a>
                @endCanBeImpersonated
            </div>
        </div>

        <a href="{{ route('directions.edit', $direction) }}"
           class="btn btn-icon edit"
           title="@lang('Edit Direction')"
           data-toggle="tooltip" data-placement="top">
            <i data-feather="edit"></i>
        </a>

        <a href="{{ route('directions.destroy', $direction) }}"
           class="btn btn-icon"
           title="@lang('Delete Direction')"
           data-toggle="tooltip"
           data-placement="top"
           data-method="DELETE"
           data-confirm-title="@lang('Please Confirm')"
           data-confirm-text="@lang('Are you sure that you want to delete this Direction?')"
           data-confirm-delete="@lang('Yes, delete him!')">
            <i data-feather="trash"></i>
        </a>
    </td>
</tr>

resources/views/direction/partials/user.blade.php
@if($create)

<div class="divider-text">@lang('Login Details')</div>

<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-3">
                <h5 class="card-title">
                    @lang('Login Details')
                </h5>
                <p class="text-muted font-weight-light">
                    @lang('Details used for authenticating with the application.')
                </p>
            </div>
            <div class="col-md-9">
                @include('user.partials.auth', ['edit' => false])
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary">
                    <i data-feather="plus"></i>
                    @lang('Add Direction')
                </button>
            </div>
        </div>
    </div>
</div>
@endif